query($BookIDProp: ID){
    Book(id: $BookIDProp){
        id
        Name
        Genre
        Author{
            Name
            Age
            id
            Books{
                Name
                id
            }
        }
    }
}